apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ingress-status-controller
  namespace: kube-system
  labels:
    application: kube-ingress-status-controller
    version: latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kube-ingress-status-controller
  template:
    metadata:
      labels:
        application: kube-ingress-status-controller
        version: latest
    spec:
      serviceAccount: kube-ingress-status-controller
      containers:
      - name: kube-ingress-status-controller
        image: mikkeloscar/kube-ingress-status-controller:latest
        resources:
          limits:
            cpu: 20m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 25Mi
